/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-10 12:21:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.partials;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<header class=\"header2\">\n");
      out.write("    <nav class=\"home-menu pure-menu pure-menu-horizontal pure-menu-fixed\">\n");
      out.write("        <a class=\"pure-menu-heading\" id=\"etrolley-header-brand\" href=\"\">e - T r o l l e y</a>\n");
      out.write("\n");
      out.write("         <ul class=\"pure-menu-list\">\n");
      out.write("                    <li class=\"pure-menu-item pure-menu-selected\"><a href=\"home.jsp\" class=\"pure-menu-link\"> Home</a></li>\n");
      out.write("                    <li class=\"pure-menu-item pure-menu-selected\"><a href=\"dashboard.jsp\" class=\"pure-menu-link\"> Dashboard</a></li>\n");
      out.write("                    <li class=\"pure-menu-item pure-menu-selected\"><a href=\"createList.jsp\" class=\"pure-menu-link\"> Create List</a></li>\n");
      out.write("                    <li class=\"pure-menu-item pure-menu-selected\"><a href=\"order-confirm.jsp\" class=\"pure-menu-link\">\n");
      out.write("                        <i class=\"fa fa-shopping-cart fa-lg\"></i>\n");
      out.write("                        Go to Trolley</a></li>\n");
      out.write("                    <li class=\"pure-menu-item pure-menu-has-children pure-menu-allow-hover\">\n");
      out.write("                        <a href=\"#\" id=\"menuLink1\" class=\"pure-menu-link\">\n");
      out.write("                            <i class=\"fa fa-cog\"></i>\n");
      out.write("                            Settings\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"pure-menu-children\">\n");
      out.write("                            <li class=\"pure-menu-item\"><a href=\"profile.jsp\" class=\"pure-menu-link\">View Profile</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"pure-menu-item pure-menu-selected\">\n");
      out.write("                        <form class=\"pure-form\" method=\"get\" action=\"supermarket-list.jsp\">\n");
      out.write("                            <input type=\"text\" class=\"pure-input-rounded\" name=\"search\" placeholder=\"Enter Supermarket...\" required>\n");
      out.write("                            <button type=\"submit\" class=\"pure-button pure-button-primary\">Search</button>\n");
      out.write("                        </form>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("    </nav>\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
